class DataConfig:
    DEFAULT_DATA_SOURCE = 'yfinance'
    DATA_UPDATE_TIME = '16:30'
    DEFUALT_HISTORY_DAYS = 365
    ALPHA_VANTAGE_CALLS_PER_MINUTE = 5
    ALPHA_VANTAGE_CALLS_PER_DAY = 25
    MAX_MISSING_DATA = 0.05

